### ISSUE TITLE
Phrasing in h26forge.pdf

### ISSUE THREAD

**Issue by PinkFreud** [wrv/wrv.github.io#1]
In the [h26forge paper](https://github.com/wrv/wrv.github.io/blob/master/h26forge.pdf), you have:

`On the basis of a guideline they call “The Rule Of 2,”
the Chrome developers try to avoid writing code that does no
more than 2 of the following: parses untrusted input, is written
in a memory-unsafe language, and runs at high privilege.`

I think you may have meant '... try to write code that does no more than 2 of the following:' - otherwise, it sounds like the Chrome devs are doing it wrong.  :)

**Comment by wrv** [comment]
Oops - thanks for catching that! Pushed a fixed version :)
